IBX-4327: Content airtime settings modal design
ibexa/admin-ui-assets pull request #14
Opened 2022-12-20 13:57 UTC by GrabowskiM

JIRA ref: https://issues.ibexa.co/browse/IBX-4327

2022-12-21 12:01 UTC, Gengar-i approved these changes

2022-12-21 13:51 UTC, dew326 requested changes

2022-12-21 13:51 UTC, dew326 commented on src/bundle/Resources/encore/ibexa.config.setup.js
> +    "@react-dom": path.resolve(
code style

2022-12-23 10:31 UTC, lucasOsti approved these changes

2023-01-10 11:18 UTC, dew326 approved these changes

2023-01-12 07:02 UTC, bogusez commented
Regression tests passed:
https://github.com/ibexa/experience/pull/123
https://github.com/ibexa/commerce/pull/193

2023-01-16 07:05 UTC, bogusez approved these changes

2023-02-02 14:08 UTC, merged