IBX-7411 Added chartjs-plugin-datalabels package
ibexa/admin-ui-assets pull request #20
Opened 2024-01-17 13:31 UTC by Gengar-i

2024-01-19 07:13 UTC, dew326 approved these changes

2024-01-19 07:14 UTC, dew326 requested changes
You have to update bin/prepare_release.sh as well

2024-01-22 14:52 UTC, tischsoic approved these changes

2024-01-22 15:50 UTC, lucasOsti approved these changes

2024-01-23 11:03 UTC, micszo approved these changes

2024-01-23 14:23 UTC, merged